CREATE TABLE NhanVien(
    idNV INT IDENTITY(1,1) PRIMARY KEY,
    MaNV NVARCHAR(10) UNIQUE,
    HoTen NVARCHAR(50) NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50) UNIQUE NOT NULL,
    SDT NVARCHAR(12) UNIQUE NOT NULL
);

CREATE TABLE KhachHang(
    MaKH NVARCHAR(10) PRIMARY KEY,
    HoTen NVARCHAR(50) UNIQUE,
    Email NVARCHAR(50) UNIQUE NOT NULL,
    SDT NVARCHAR(12) UNIQUE NOT NULL
);

CREATE TABLE DonHang(
    MaDH NVARCHAR(10) PRIMARY KEY,
    MaNV NVARCHAR(10),
    MaKH NVARCHAR(10),
    Ngay DATE NOT NULL,
    TongTien DECIMAL(10,2) NOT NULL,
    FOREIGN KEY(MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE SanPham(
    MaSP NVARCHAR(10) PRIMARY KEY,
    TenSP NVARCHAR(50),
    Gia DECIMAL(10,2) NOT NULL,
    SoLuongTon INT,
    NgayNhap DATE NOT NULL
);

CREATE TABLE KhuyenMai(
    MaKM NVARCHAR(10) PRIMARY KEY,
    TenKM NVARCHAR(10)
)

CREATE TABLE ChiTietKM(
    MaKM NVARCHAR(10),
	MaSP nvarchar(10),
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    TiLeGiam INT NOT NULL,
    GiamToiDa DECIMAL(10,2)
	primary key(MaSP, MaKM)
	FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
    FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM)
)
CREATE TABLE ChiTietDonHang(
    MaDH NVARCHAR(10),
    MaSP NVARCHAR(10),
    GiaBan DECIMAL(10,2) NOT NULL,
    SoLuong INT NOT NULL,
    MaKM NVARCHAR(10),
	PRIMARY KEY (MaDH, MaSP),
	FOREIGN KEY (MaKM) references KhuyenMai(MaKM),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH) ON DELETE CASCADE,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

CREATE TABLE Log(
    ID INT PRIMARY KEY IDENTITY(1,1),
    Activity VARCHAR(255) NOT NULL,
    MaNV NVARCHAR(10),
    Ngay DATE NOT NULL,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
)

insert into NhanVien(idNV, MaNV, HoTen, ChucVu, Email, SDT)
values(1, N'001', N'Nguy?n V?n A', N'Nhân Viên', N'nguyenvana@gmail.com', N'0123456789');